name: eq_xprinter
description: A Flutter plugin for controlling XPrinter thermal printers on Android. This plugin allows communication with XPrinter devices over Bluetooth for printing images.
version: 0.0.1
homepage: https://github.com/eq-devs/xprinter
repository: https://github.com/eq-devs/xprinter
issue_tracker: https://github.com/eq-devs/xprinter/issues

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eq.xprinter
        pluginClass: XprinterPlugin